```{r}
library(tidyverse)
library(skimr)
library(survival)
library(survminer)
library(fitdistrplus)

root = 'C://Users//corma//Documents//GitHub//WW2_Analysis//'
setwd(root)
```
```{r}
# read in the survival analysis data
uboats = read_csv("uboats_cleaned.csv")

# if Sunk, Scuttled, Surrendered, Captured, or Missing, then 1, else 0
uboats = uboats %>%
  mutate(event = ifelse(Fate_Event %in% c("Sunk"), 1, 0), notable = ifelse(`Notable Commanders` != 'NA', 1, 0))
uboats = uboats %>%
  mutate(notable = ifelse(is.na(notable), 0, notable),
         commish_year = as.numeric(str_sub(Commissioned, 1, 4)),
         # if commissioned before after the start of WW2 then 'WW2' else 'Interwar'
         war = ifelse(as.Date(Commissioned) < as.Date('1939-09-01'), 'Interwar', 'WW2')) %>%
  filter(Active_Service > 0) %>%
  drop_na(Active_Service, event)
top_5_types = uboats %>% filter(Type %in% c("VIIC", "XXI", "VIIC/41", "IXC/40", "XXIII"))
```
```{r}
# now active service
overall_fit = survfit(Surv(Active_Service, event) ~ Type, data = top_5_types %>% filter(Type %in% c("VIIC", "XXI", "VIIC/41", "IXC/40", "XXIII")))
ggsurvplot(overall_fit, data = top_5_types, pval = TRUE, surv.median.line = "hv", conf.int = TRUE) + ggtitle("KM curve for U-Boats by Type")
```

```{r}
# perform a test to see if uboats with notable commanders last longer
overall_fit = survfit(Surv(Active_Service, event) ~ notable, data = uboats)
ggsurvplot(overall_fit, data = uboats, pval = TRUE, surv.median.line = "hv", conf.int = TRUE) + ggtitle("KM curve for U-Boats with Notable Commanders")
```

```{r}
# a km curve for commissioned years
year_fit = survfit(Surv(Active_Service, event) ~ war, data = uboats)
ggsurvplot(year_fit, data = uboats, pval = TRUE, surv.median.line = "hv", conf.int = TRUE) + ggtitle("KM curve for U-Boats by War")
```


----------------------
# Model Fitting
```{r}
gen_model = function(data, model_formula, dist_name, model_name) {
  # Convert model_formula to a formula object
  print(model_name)
  formula_obj = as.formula(paste("Surv(Lifespan, event) ~", model_formula))
  # Fit the survival regression model
  model = survreg(formula_obj, data = data, dist = dist_name)

  # Predict the values using the model
  pred = predict(model, newdata = data, type = "response")

  # Calculate SSRES
  ssres = sum((data$Active_Service - pred)^2)
  # Calculate SSTOT
  sstot = sum((data$Active_Service - mean(data$Active_Service))^2)
  # Compute R²
  rsq = 1 - (ssres / sstot)

  # Calculate mean squared error (MSE)
  mse = mean((data$Active_Service - pred)^2)

  # Calc aic
  aic = AIC(model)


  return(list(model = model, mse = mse, rsq = rsq, aic = aic, dist_name = model_name))
}
```
# models:
## notable
## notable + Type
## notable + Type
## notable + Type  + commish_year
## notable + Type  + commish_year + war:Type
## notable + Type  + commish_year + war:Type + war:commish_year
## notable + Type  + commish_year + war:Type + war:commish_year + Type:commish_year

```{r}
# fit the models
models = list()
model_todo_list = c("extreme", "logistic", "gaussian", "weibull", "exponential", "rayleigh", "loggaussian", "lognormal", "loglogistic", "t")
for (model_name in model_todo_list) {
  models[[length(models) + 1]] = gen_model(top_5_types, "notable", model_name, paste("notable:", model_name))
  models[[length(models) + 1]] = gen_model(top_5_types, "notable + Type", model_name, paste("notable+Type:", model_name))
  models[[length(models) + 1]] = gen_model(top_5_types, 'notable + commish_year', model_name, paste("notable+commish_year:", model_name))
  models[[length(models) + 1]] = gen_model(top_5_types, "notable + Type +  commish_year", model_name, paste("notable+Type+commish_year:", model_name))
  models[[length(models) + 1]] = gen_model(top_5_types, "notable + Type +  commish_year + Type:commish_year", model_name, paste("notable+Type+Type*commish_year:", model_name))
}
```
```{r}
best_score = 0
best_model = NULL
for (model in models) {
  # check not na for rsq
  if (is.na(model$aic)) {
    next
  }
  if (model$aic > best_score) {
    best_score = model$aic
    best_model = model
  }
}
best_score = -10
best_rsq_model = NULL
for (model in models) {
  # check not na for rsq
  if (is.na(model$rsq)) {
    next
  }
  if (model$rsq > best_score) {
    best_score = model$rsq
    best_rsq_model = model
  }
}

print(best_model$dist_name)
print(best_model$aic)
print(best_model$rsq)

# check if best model and best_rsq_model are the same
if (best_model$dist_name == best_rsq_model$dist_name) {
  print("Best model and best rsq model are the same")
} else {
  print(best_rsq_model$dist_name)
  print(best_rsq_model$rsq)
  print(best_rsq_model$aic)
}
```
```{r}
# plot predicted vs actual
pred = predict(best_model$model, newdata = top_5_types, type = "response")
top_5_types = top_5_types %>% mutate(pred = pred)
top_5_types %>% ggplot() +
  geom_point(aes(x = Active_Service, y = pred)) +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Predicted vs Actual Active Service", x = "Actual", y = "Predicted") +
  theme_minimal()
```
```{r}
# cause a error onpupose
```
```{r}
# create a weighted best model
w_best_model = NULL

# Create a data frame from the list of models
model_metrics = do.call(rbind, lapply(models, function(model) {
  data.frame(
    dist_name = model$dist_name,
    mse = model$mse,
    aic = model$aic,
    rsq = model$rsq
  )
}))
```
```{r}

# for r2, mse and aic we want to minimize
top_r2 = model_metrics %>% arrange(desc(rsq))
top_mse = model_metrics %>% arrange(mse)
top_aic = model_metrics %>% arrange(aic)
```
```{r}


# given the position of each model, we will assign a its index as its weight, the further down the higher the weight
# our best model will be the one with the lowest weighted score

# assign weights
for (i in seq_len(nrow(top_r2))) {
  top_r2[i, "weight"] = i
  top_mse[i, "weight"] = i
  top_aic[i, "weight"] = i
}
```
```{r}

all_models = list(top_r2, top_mse, top_aic)
# Initialize all_best_models as an empty data frame
all_best_models <- data.frame(dist_name = character(), mse = numeric(), aic = numeric(), rsq = numeric(), weight = numeric(), stringsAsFactors = FALSE)
```
```{r}

# Iterate through the models and update weights
for (model_lis in all_models) {
  for (model in model_lis) {
    print(is.null(all_best_models))
    if (is.null(all_best_models)) {
      all_best_models = model
    } else {
      # Check if the model doesn't appear in the df all_best_models
      if (model$dist_name %in% all_best_models$dist_name) {
        # If it does appear, add their weights and update all_best_models
        all_best_models[all_best_models$dist_name == model$dist_name, "weight"] <-
          all_best_models[all_best_models$dist_name == model$dist_name, "weight"] + model$weight
      } else {
        all_best_models = rbind(all_best_models, model)
      }
    }
  }
}
```
```{r}

# sort the list by weight
all_best_models = all_best_models %>% arrange(weight)
# get the best model
w_best_model = all_best_models[[1]]
print(w_best_model$dist_name)
print(w_best_model$aic)
print(w_best_model$rsq)
```
```{r}
head(all_best_models)
```
```{r}
models = model_metrics
# rearange models by aic
models = models %>% arrange(aic)
# add a col weight, which is their index
models = models %>% mutate(weight = 1:nrow(models))
# arrange by rsq
models = models %>% arrange(desc(rsq))
# add a col weight, which is their index
models = models %>% mutate(weight = weight + 1:nrow(models))
# arrange by mse
models = models %>% arrange(mse)
# add a col weight, which is their index
models = models %>% mutate(weight = weight + 1:nrow(models))
```
```{r}
# arrange by weight
models = models %>% arrange(weight)
best_model_name = models[[1]]$dist_name
best_model_aic = models[[1]]$aic
best_model_rsq = models[[1]]$rsq
best_model_weight = models[[1]]$weight
print(best_model_name)
print(best_model_aic)
print(best_model_rsq)
print(best_model_weight)
```
```{r}
head(models)
```

--------------
```{r}
model_todo_list = c("extreme", "logistic", "gaussian", "weibull", "exponential", "rayleigh", "loggaussian", "lognormal", "loglogistic", "t")
mode_features = c("notable",
                  "Type",
                  "commish_year",
                  "Last_Floatilla",
                  "war:Type",
                  "war:commish_year",
                  "Type:commish_year",
                  "war:Type:commish_year")
recurse_models = function(data, model_formula, model_name, mode_features) {
  models = c()

  for (mode_feature in mode_features) {
    model_formula = paste(mode_feature, collapse = " + ")
    reduced_feats = setdiff(mode_features, mode_feature)
    models = c(models, c(model_formula, model_name))
    gen_model(data, model_formula, model_name, reduced_feats)
  }
  return(models)
}
models_list = c()
for (model_name in model_todo_list) {
  models_list = c(models_list, recurse_models(uboats, '', model_name, mode_features))
}
models_list
```