```{r}
library(tidyverse)
library(skimr)
library(survival)
library(survminer)
library(fitdistrplus)

root = 'C://Users//corma//Documents//GitHub//WW2_Analysis//u-boat_analysis.rmd'
```
```{r}
uboats = read_csv("uboats_cleaned.csv")
skim(uboats)
```
```{r}
# drop rows with NA Active_Service and Lifespan
# uboats = uboats %>%
#   drop_na(Active_Service, Lifespan)
# skim(uboats)
```
```{r}
colnames(uboats)
```
[1] "Name"
[2] "Year"
[3] "Type"
[4] "Notable Commanders"
[5] "Warships_sunk_n_total_loss_No"
[6] "Warships_sunk_n_total_loss_Tons-n-GRT"
[7] "Warships_Damaged_No"
[8] "Warships_Damaged_Tons-n-GRT"
[9] "Merchant_Ships_sunk_No"
[10] "Merchant_Ships_sunk_GRT"
[11] "Merchant_Ships_damaged_No"
[12] "Merchant_Ships_damaged_GRT"
[13] "Merchant_Ships_total_loss_No"
[14] "Merchant_Ships_total_loss_GRT"
[15] "Fate_Event"
[16] "Fate_Date"
[17] "Notes"
[18] "URL"
[19] "Commissioned"
[20] "Lifespan"
[21] "Active_Service"

```{r}
# select Name, Type, Fate_Event, Notes, Lifespan, and Active_Service for Survival analysis
uboats_SA = uboats %>%
  dplyr::select(Name, Type, Fate_Event, Notes, Lifespan, Active_Service, 'Notable Commanders')
```
```{r}
# show the unique fates, graph by count
fate_counts = uboats_SA %>%
  count(Fate_Event) %>%
  arrange(desc(n))

fate_counts %>% ggplot() +
  geom_col(aes(x = reorder(Fate_Event, n), y = n), fill = '#3D9970', color = 'black') +
  coord_flip() +
  labs(title = "Unique Fates of U-Boats", x = "Fate", y = "Count") +
  theme_classic() +
  theme(text = element_text(family = "serif"),
        title = element_text(face = "bold", size = 18),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.x = element_text(face = "bold", size = 12),
        axis.text.y = element_text(face = "bold", size = 12))
```
```{r}
# if Sunk, Scuttled, or Surrendered, then 1, else 0
uboats_SA['Status'] = ifelse(grepl("Sunk|Scuttled|Surrendered", uboats_SA$Fate_Event), 1, 0)
```

```{r}
# create a km curve
km_fit = survfit(Surv(Active_Service, Status) ~ 1, data = uboats_SA)
summary(km_fit)
```
```{r}
# drop /n from Type
uboats_SA$Type = gsub("\n", "", uboats_SA$Type)
unique_types = unique(uboats_SA["Type"])
unique_types
```
```{r}
# graph unique types by count
type_counts = uboats_SA %>%
  count(Type) %>%
  arrange(desc(n))

type_counts %>% ggplot() +
  geom_col(aes(x = reorder(Type, n), y = n), fill = '#3D9970', color = 'black') +
  coord_flip() +
  labs(title = "Unique Types of U-Boats", x = "Type", y = "Count") +
  theme_classic() +
  theme(text = element_text(family = "serif"),
        title = element_text(face = "bold", size = 18),
        axis.title.x = element_text(face = "bold", size = 14),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.text.x = element_text(face = "bold", size = 12),
        axis.text.y = element_text(face = "bold", size = 12)
  )
```
```{r}
# type_viic = uboats_SA %>%
#   filter(Type == "VIIC")
# viic_fit = survfit(Surv(Active_Service, Status) ~ 1, data = type_viic)
# ggsurvplot(viic_fit, data = type_viic, palette = "YlOrRd", risk.table = F, conf.int = T) +
#   labs(title = "Survival of VIIC U-Boats", x = "Active Service (Years)")

type_km = function(utype, table) {
  type_table = table %>% filter(Type == utype)
  type_fit = survfit(Surv(Active_Service, Status) ~ 1, data = type_table)
  ggsurvplot(type_fit, data = type_table, palette = "YlOrRd", risk.table = F, conf.int = T) +
    labs(title = "Survival of VIIC U-Boats", x = "Active Service (Years)")
}
```
```{r}
# calculate avg lifespan for uboast for each Year
uboats %>%
        group_by(Year) %>%
        summarise(avg_lifespan = mean(Lifespan, na.rm = TRUE)) %>%
        ggplot() +
        geom_col(aes(x = Year, y = avg_lifespan), fill = '#3D9970', color = 'black') +
        theme_classic() +
        labs(title = "Average Lifespan of U-Boats by Year", x = "Year", y = "Average Lifespan") +
        theme(text = element_text(family = "serif"),
              title = element_text(face = "bold", size = 18),
              axis.title.x = element_text(face = "bold", size = 14),
              axis.title.y = element_text(face = "bold", size = 14),
              axis.text.x = element_text(face = "bold", size = 10),
              axis.text.y = element_text(face = "bold", size = 10),
              legend.position = "none")
```

```{r}
# look at the distribution of lifespan
ggplot(uboats, aes(x = Lifespan)) +
        geom_histogram(binwidth = 100, fill = '#3D9970', color = 'black') +
        theme_classic() +
        labs(title = 'Lifespan of U-Boats', x = 'Lifespan (Days)', y = 'Count') +
        theme(text = element_text(family = "serif"),
              title = element_text(face = "bold", size = 18),
              axis.title.x = element_text(face = "bold", size = 14),
              axis.title.y = element_text(face = "bold", size = 14),
              axis.text.x = element_text(face = "bold", size = 12),
              axis.text.y = element_text(face = "bold", size = 12))
```
```{r}
# plot patrols as a hist
ggplot(uboats, aes(x = Patrols_Count)) +
        geom_histogram(binwidth = 1, fill = '#3D9970', color = 'black') +
        theme_classic() +
        labs(title = 'Patrols of U-Boats', x = 'Patrols', y = 'Count') +
        theme(text = element_text(family = "serif"),
              title = element_text(face = "bold", size = 18),
              axis.title.x = element_text(face = "bold", size = 14),
              axis.title.y = element_text(face = "bold", size = 14),
              axis.text.x = element_text(face = "bold", size = 12),
              axis.text.y = element_text(face = "bold", size = 12))
```
```{r}
# group by last flotilla and graph the count of rows
uboats %>%
        filter(event == 1) %>%
        group_by(Last_Flotilla) %>%
        summarise(count = n()) %>%
        arrange(desc(count)) %>%
        # head(5) %>%
        ggplot(aes(y = reorder(Last_Flotilla, count), x = count)) +
        geom_bar(stat = "identity", fill = "#3D9970") +
        theme_classic() +
        labs(title = "Flotillas Losses by Count", x = "Count", y = "Last Flotilla") +
        theme(text = element_text(family = "serif"),
                      title = element_text(face = "bold", size = 18),
                      axis.title.x = element_text(face = "bold", size = 14, angle = 90, hjust = 1),
                      axis.title.y = element_text(face = "bold", size = 14),
                      axis.text.x = element_text(face = "bold", size = 12),
                      axis.text.y = element_text(face = "bold", size = 12))
```
```{r}
# group by patrol count, calc the mean of wolfpacks for each (ignore 0s)
uboats %>%
        # filter(Patrols_Count > 0) %>%
        group_by(Patrols_Count) %>%
        summarise(avg_wolfpacks = mean(Wolfpacks_Count, na.rm = TRUE)) %>%
        ggplot() +
        geom_col(aes(x = Patrols_Count, y = avg_wolfpacks), fill = '#3D9970', color = 'black') +
        theme_classic() +
        labs(title = "Average Wolfpacks by Patrol Count", x = "Patrol Count", y = "Average Wolfpacks") +
        theme(text = element_text(family = "serif"),
              title = element_text(face = "bold", size = 18),
              axis.title.x = element_text(face = "bold", size = 14),
              axis.title.y = element_text(face = "bold", size = 14),
              axis.text.x = element_text(face = "bold", size = 10),
              axis.text.y = element_text(face = "bold", size = 10),
              legend.position = "none")
```

## notable commanders analysis
```{r}
# read in the notable commanders data
notable_commanders = read_csv("uboat_commanders.csv")

```
```{r}

```
